spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: test
    password: root
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.8.123:3306/shop_test
zzc: test1
