spring:
  application:
    name: product
  datasource:
    name: test
    url: jdbc:mysql://192.168.8.123:3306/shop_test
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
zzc: test
